name: huellas_salud_movil
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.0




dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  logger: ^2.6.1
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.1.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  provider: ^6.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




flutter:
  uses-material-design: true
  assets:
    - assets/img/logos/
    - assets/img/images/


flutter_icons:
  android: "huellas_salud_movil"
  ios: true
  image_path: "assets/img/icons/icon_app.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/icons/icon_app.png"
  remove_alpha_ios: true
  min_sdk_android: 21